"""add wider column set for PO and line items

Revision ID: 27faf7d1ee98
Revises: 773f4f1d784f
Create Date: 2026-09-06 10:18:23.984606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27faf7d1ee98'
down_revision: Union[str, None] = '773f4f1d784f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('po_line_items', sa.Column('uom', sa.String(length=32), nullable=True))
    op.add_column('po_line_items', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('po_line_items', sa.Column('weight', sa.String(length=64), nullable=True))
    op.add_column('po_line_items', sa.Column('item_category', sa.String(length=128), nullable=True))
    op.add_column('po_line_items', sa.Column('item_code', sa.String(length=128), nullable=True))
    op.add_column('po_line_items', sa.Column('equipment_name', sa.String(length=255), nullable=True))
    op.add_column('po_line_items', sa.Column('drawing_number', sa.String(length=255), nullable=True))
    op.add_column('po_line_items', sa.Column('section', sa.String(length=128), nullable=True))
    op.add_column('po_line_items', sa.Column('warranty_applicable', sa.String(length=16), nullable=True))
    op.add_column('po_line_items', sa.Column('warranty_period_days', sa.String(length=32), nullable=True))
    op.add_column('po_line_items', sa.Column('hazardous_material', sa.String(length=16), nullable=True))
    op.add_column('po_line_items', sa.Column('oem_item', sa.String(length=16), nullable=True))
    op.add_column('po_line_items', sa.Column('export_control', sa.String(length=16), nullable=True))
    op.add_column('po_line_items', sa.Column('lead_days', sa.String(length=32), nullable=True))
    op.add_column('po_line_items', sa.Column('remarks_to_vendor', sa.String(length=1000), nullable=True))
    op.add_column('po_line_items', sa.Column('remarks_from_office', sa.String(length=1000), nullable=True))
    op.add_column('po_line_items', sa.Column('remarks_from_vessel', sa.String(length=1000), nullable=True))
    op.add_column('purchase_orders', sa.Column('operating_unit', sa.String(length=128), nullable=True))
    op.add_column('purchase_orders', sa.Column('coupa_po_number', sa.String(length=128), nullable=True))
    op.add_column('purchase_orders', sa.Column('tag_name', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('logistic_priority', sa.String(length=64), nullable=True))
    op.add_column('purchase_orders', sa.Column('process', sa.String(length=128), nullable=True))
    op.add_column('purchase_orders', sa.Column('po_type', sa.String(length=128), nullable=True))
    op.add_column('purchase_orders', sa.Column('po_location', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('requisition_no', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('enquiry_no', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('grn_no', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('do_no', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('equipment', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('owner_approved', sa.String(length=16), nullable=True))
    op.add_column('purchase_orders', sa.Column('post_invoice', sa.String(length=16), nullable=True))
    op.add_column('purchase_orders', sa.Column('port_schedule_status', sa.String(length=128), nullable=True))
    op.add_column('purchase_orders', sa.Column('revision_no', sa.String(length=64), nullable=True))
    op.add_column('purchase_orders', sa.Column('cost_centre_wbs', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('account_re_allocation', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('analysis_code', sa.String(length=128), nullable=True))
    op.add_column('purchase_orders', sa.Column('quote', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('ar_invoice_no', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('expected_delivery_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('deadline_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('afe_approved_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('eff_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('est_vessel_delivery', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('org_commit_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'org_commit_date')
    op.drop_column('purchase_orders', 'est_vessel_delivery')
    op.drop_column('purchase_orders', 'eff_date')
    op.drop_column('purchase_orders', 'afe_approved_date')
    op.drop_column('purchase_orders', 'closed_date')
    op.drop_column('purchase_orders', 'deadline_date')
    op.drop_column('purchase_orders', 'delivery_date')
    op.drop_column('purchase_orders', 'expected_delivery_date')
    op.drop_column('purchase_orders', 'issue_date')
    op.drop_column('purchase_orders', 'ar_invoice_no')
    op.drop_column('purchase_orders', 'quote')
    op.drop_column('purchase_orders', 'analysis_code')
    op.drop_column('purchase_orders', 'account_re_allocation')
    op.drop_column('purchase_orders', 'cost_centre_wbs')
    op.drop_column('purchase_orders', 'revision_no')
    op.drop_column('purchase_orders', 'port_schedule_status')
    op.drop_column('purchase_orders', 'post_invoice')
    op.drop_column('purchase_orders', 'owner_approved')
    op.drop_column('purchase_orders', 'equipment')
    op.drop_column('purchase_orders', 'do_no')
    op.drop_column('purchase_orders', 'grn_no')
    op.drop_column('purchase_orders', 'enquiry_no')
    op.drop_column('purchase_orders', 'requisition_no')
    op.drop_column('purchase_orders', 'po_location')
    op.drop_column('purchase_orders', 'po_type')
    op.drop_column('purchase_orders', 'process')
    op.drop_column('purchase_orders', 'logistic_priority')
    op.drop_column('purchase_orders', 'tag_name')
    op.drop_column('purchase_orders', 'coupa_po_number')
    op.drop_column('purchase_orders', 'operating_unit')
    op.drop_column('po_line_items', 'remarks_from_vessel')
    op.drop_column('po_line_items', 'remarks_from_office')
    op.drop_column('po_line_items', 'remarks_to_vendor')
    op.drop_column('po_line_items', 'lead_days')
    op.drop_column('po_line_items', 'export_control')
    op.drop_column('po_line_items', 'oem_item')
    op.drop_column('po_line_items', 'hazardous_material')
    op.drop_column('po_line_items', 'warranty_period_days')
    op.drop_column('po_line_items', 'warranty_applicable')
    op.drop_column('po_line_items', 'section')
    op.drop_column('po_line_items', 'drawing_number')
    op.drop_column('po_line_items', 'equipment_name')
    op.drop_column('po_line_items', 'item_code')
    op.drop_column('po_line_items', 'item_category')
    op.drop_column('po_line_items', 'weight')
    op.drop_column('po_line_items', 'brand')
    op.drop_column('po_line_items', 'uom')
    # ### end Alembic commands ###
