"""Add 19 new PO list columns

Revision ID: 2c954c621af8
Revises: 9e8b54afcda9
Create Date: 2026-09-07 13:43:04.276151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c954c621af8'
down_revision: Union[str, None] = '9e8b54afcda9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('local_purchase', sa.String(length=64), nullable=True))
    op.add_column('purchase_orders', sa.Column('actioned_on', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('forwarded_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('value_of_interfaced_qty', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('purchase_orders', sa.Column('insurance_claim_no', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('transfer_method', sa.String(length=128), nullable=True))
    op.add_column('purchase_orders', sa.Column('organisation_assignment', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('po_update', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('afe_po', sa.String(length=128), nullable=True))
    op.add_column('purchase_orders', sa.Column('afe_status', sa.String(length=128), nullable=True))
    op.add_column('purchase_orders', sa.Column('approved_by', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('invoice_status', sa.String(length=128), nullable=True))
    op.add_column('purchase_orders', sa.Column('schd_delivery_port', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('vessel_eta', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('post_invoice_remarks', sa.Text(), nullable=True))
    op.add_column('purchase_orders', sa.Column('asn_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('purchase_orders', sa.Column('send_reminder', sa.String(length=128), nullable=True))
    op.add_column('purchase_orders', sa.Column('recharge_applicable_to', sa.String(length=255), nullable=True))
    op.add_column('purchase_orders', sa.Column('recharge', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'recharge')
    op.drop_column('purchase_orders', 'recharge_applicable_to')
    op.drop_column('purchase_orders', 'send_reminder')
    op.drop_column('purchase_orders', 'asn_date')
    op.drop_column('purchase_orders', 'post_invoice_remarks')
    op.drop_column('purchase_orders', 'vessel_eta')
    op.drop_column('purchase_orders', 'schd_delivery_port')
    op.drop_column('purchase_orders', 'invoice_status')
    op.drop_column('purchase_orders', 'approved_by')
    op.drop_column('purchase_orders', 'afe_status')
    op.drop_column('purchase_orders', 'afe_po')
    op.drop_column('purchase_orders', 'po_update')
    op.drop_column('purchase_orders', 'organisation_assignment')
    op.drop_column('purchase_orders', 'transfer_method')
    op.drop_column('purchase_orders', 'insurance_claim_no')
    op.drop_column('purchase_orders', 'value_of_interfaced_qty')
    op.drop_column('purchase_orders', 'forwarded_date')
    op.drop_column('purchase_orders', 'actioned_on')
    op.drop_column('purchase_orders', 'local_purchase')
    # ### end Alembic commands ###
