"""init

Revision ID: 773f4f1d784f
Revises: 
Create Date: 2026-09-04 15:07:55.778524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '773f4f1d784f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('vessel', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('po_send_status', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('items_count', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_reference', sa.String(length=255), nullable=True),
    sa.Column('base_currency_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('exch_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('priority', sa.String(length=64), nullable=True),
    sa.Column('delivery_port', sa.String(length=255), nullable=True),
    sa.Column('payment', sa.String(length=64), nullable=True),
    sa.Column('payment_due_after_days', sa.Integer(), nullable=True),
    sa.Column('budget_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entity', sa.String(length=255), nullable=True),
    sa.Column('delivery_to', sa.String(length=255), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('readiness_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('delivery_terms', sa.String(length=255), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('attachments_count', sa.Integer(), nullable=True),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('list_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_approved_date'), 'purchase_orders', ['approved_date'], unique=False)
    op.create_index(op.f('ix_purchase_orders_category'), 'purchase_orders', ['category'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vessel'), 'purchase_orders', ['vessel'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.Enum('FULL', 'LIST_ONLY', 'DETAIL_ONLY', 'RESUME', name='scrape_run_type'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL_FAILURE', 'FAILED', name='scrape_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_pos_found', sa.Integer(), nullable=True),
    sa.Column('pos_succeeded', sa.Integer(), nullable=True),
    sa.Column('pos_failed', sa.Integer(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('po_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('s_no', sa.Integer(), nullable=True),
    sa.Column('part_number', sa.String(length=128), nullable=True),
    sa.Column('item_description', sa.String(length=1000), nullable=True),
    sa.Column('rob', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('account_code', sa.String(length=255), nullable=True),
    sa.Column('plate_drawing_number', sa.String(length=255), nullable=True),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id', 's_no', name='uq_po_line_item_po_sno')
    )
    op.create_table('scrape_row_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scrape_run_id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_row_errors_po_number'), 'scrape_row_errors', ['po_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_row_errors_po_number'), table_name='scrape_row_errors')
    op.drop_table('scrape_row_errors')
    op.drop_table('po_line_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scrape_runs')
    op.drop_index(op.f('ix_purchase_orders_vessel'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_category'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_approved_date'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
