"""Add missing line item columns

Revision ID: 9e8b54afcda9
Revises: 27faf7d1ee98
Create Date: 2026-09-07 12:34:38.176301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8b54afcda9'
down_revision: Union[str, None] = '27faf7d1ee98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('po_line_items', sa.Column('readiness_date', sa.String(length=64), nullable=True))
    op.add_column('po_line_items', sa.Column('vendor_remarks', sa.String(length=1000), nullable=True))
    op.add_column('po_line_items', sa.Column('item_subsection', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('po_line_items', 'item_subsection')
    op.drop_column('po_line_items', 'vendor_remarks')
    op.drop_column('po_line_items', 'readiness_date')
    # ### end Alembic commands ###
