"""Add vendor_email

Revision ID: db315e7c1e1e
Revises: ed4441c886c5
Create Date: 2026-09-24 17:45:18.375556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db315e7c1e1e'
down_revision: Union[str, None] = 'ed4441c886c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('vendor_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'vendor_email')
    # ### end Alembic commands ###
